# yaml-language-server: $schema=https://aka.ms/dsc/schemas/v3/bundled/config/document.vscode.json
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
- name: ConfigureFirewall
  type: Microsoft.Windows/Registry
  properties:
    _exist: true
    keyPath: HKLM\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\StandardProfile
    valueName: EnableFirewall
    valueData:
      DWord: FIREWALL_VALUE